name: smeapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7  
  provider: ^6.0.5
  http: ^1.3.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  fl_chart: ^0.71.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/4.jpg
    - assets/images/logingpage.jpg
    - assets/images/backgro.jpg
    - assets/images/woodh.jpg
    - assets/images/beeralu2.jpg
    - assets/images/laakshah.jpg
    - assets/images/potteryho.jpg
    - assets/images/bathikh.jpg
    - assets/images/math.jpg
    - assets/images/jewelleryh.jpg
    - assets/images/backgro.jpg
    - assets/images/9.jpg
    - assets/images/srilanka.jpg
