// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkpwHES4vmdijPCTnV002L4UJSxWSsI9w',
    appId: '1:220539978211:web:26fbcae48a2cbd6a09a0d6',
    messagingSenderId: '220539978211',
    projectId: 'smeapp-db795',
    authDomain: 'smeapp-db795.firebaseapp.com',
    storageBucket: 'smeapp-db795.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7lxASRMRZ8WNhcw8WymF08DGJhevthR8',
    appId: '1:220539978211:android:80513c96f5889c6709a0d6',
    messagingSenderId: '220539978211',
    projectId: 'smeapp-db795',
    storageBucket: 'smeapp-db795.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2fLi4tc6pahwM4fTVxcSkI-mqDoJ6dmk',
    appId: '1:220539978211:ios:480ee989438b091509a0d6',
    messagingSenderId: '220539978211',
    projectId: 'smeapp-db795',
    storageBucket: 'smeapp-db795.firebasestorage.app',
    iosBundleId: 'com.example.smeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2fLi4tc6pahwM4fTVxcSkI-mqDoJ6dmk',
    appId: '1:220539978211:ios:480ee989438b091509a0d6',
    messagingSenderId: '220539978211',
    projectId: 'smeapp-db795',
    storageBucket: 'smeapp-db795.firebasestorage.app',
    iosBundleId: 'com.example.smeapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkpwHES4vmdijPCTnV002L4UJSxWSsI9w',
    appId: '1:220539978211:web:7cba22bab57d9bcb09a0d6',
    messagingSenderId: '220539978211',
    projectId: 'smeapp-db795',
    authDomain: 'smeapp-db795.firebaseapp.com',
    storageBucket: 'smeapp-db795.firebasestorage.app',
  );

}